export const TRUSTPILOT_BUSINESS_ID = process.env.NEXT_PUBLIC_TRUSTPILOT_BUSINESS_ID ?? "";

export const TRUSTPILOT_REVIEW_URL = process.env.NEXT_PUBLIC_TRUSTPILOT_REVIEW_URL ?? "";

export const TRUSTPILOT_TEMPLATE_ID = "5419b6ffb0d04a076446a9af";
